### PR TITLE
Test against Rails 5

### PR DESCRIPTION
**Pull request by greysteil**
Now Rails 5 has a release candidate we should start testing against it.

### CODE REVIEW

**Comment by greysteil** [comment]
@lawrencejones - can you review?

**Comment by lawrencejones** [comment]
Looks good to me! 👍

**Comment by greysteil** [comment]
Awesome. You OK to cut a patch release for it? Keen to get us unblocked to test PS against Rails 5.

**Comment by lawrencejones** [comment]
Yup, that's fine https://github.com/gocardless/coach/pull/14

**Pull request merged**
