### PR TITLE
Pin rubocop like we mean it

### PR DESCRIPTION
**Pull request by greysteil**
Bumping rubocop is an issue for another PR...

### CODE REVIEW

**Comment by greysteil** [comment]
@lawrencejones - FYI.

**Comment by lawrencejones** [comment]
Ruby 2.1 is EoL, so let's ditch support for that. Hopefully that'll give a clean bill of health for Travis!

**Comment by greysteil** [comment]
Fingers crossed. Gave the `travis.yml` a quick spring clean in the process.

**Comment by lawrencejones** [comment]
Think we need to pin the Ruby versions to the exact patch :(

**Comment by greysteil** [comment]
💃 🏆 🎉

**Comment by lawrencejones** [comment]
Huzzah!

**Comment by lawrencejones** [comment]
I've built 0.4.5 and published it to Rubygems with both #17 and #18. Let me know if everything looks good!

**Comment by greysteil** [comment]
Works like a charm. Thanks @lawrencejones!

**Pull request merged**
